# Generated by Django 4.1.1 on 2022-12-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="appliedLeavesDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ticket_No", models.IntegerField()),
                ("Current_Shop", models.CharField(max_length=100)),
                ("Cost_Center_Name", models.CharField(max_length=100)),
                ("leave_duration", models.CharField(max_length=100)),
                ("leave_type", models.CharField(max_length=100)),
                ("on_date", models.DateField()),
                ("applied_on_date_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="approvedLeavesDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ticket_No", models.IntegerField()),
                ("Current_Shop", models.CharField(max_length=100)),
                ("Cost_Center_Name", models.CharField(max_length=100)),
                ("leave_duration", models.CharField(max_length=100)),
                ("leave_type", models.CharField(max_length=100)),
                ("on_date", models.DateField()),
                ("approved_on_date_time", models.DateTimeField(null=True)),
                ("approved_by", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="cumulativeLeavesDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ticket_No", models.IntegerField()),
                ("Complete_Name", models.CharField(max_length=80)),
                ("Current_Shop", models.CharField(max_length=100, null=True)),
                ("Cost_Center_Name", models.CharField(max_length=100, null=True)),
                ("leave_type", models.CharField(max_length=100)),
                ("leave_duration", models.CharField(max_length=100)),
                ("from_date", models.DateField()),
                ("applied_on_date", models.DateField(auto_now_add=True, null=True)),
                ("to_date", models.DateField()),
                ("status", models.IntegerField(default=0)),
                ("reason", models.CharField(default="", max_length=255)),
                ("action_by", models.CharField(default="", max_length=80)),
            ],
            options={
                "verbose_name": "Leave",
                "verbose_name_plural": "Leaves",
                "ordering": ["-applied_on_date"],
            },
        ),
        migrations.CreateModel(
            name="delapprovedLeavesDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ticket_No", models.IntegerField()),
                ("Current_Shop", models.CharField(max_length=100)),
                ("Cost_Center_Name", models.CharField(max_length=100)),
                ("leave_duration", models.CharField(max_length=100)),
                ("leave_type", models.CharField(max_length=100)),
                ("on_date", models.DateField()),
                ("approved_on_date_time", models.DateTimeField(null=True)),
                ("approved_by", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="holidayList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_today", models.DateField()),
                (
                    "type_of_holiday",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(default="Not Updated", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="leavesDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ticket_No", models.IntegerField()),
                ("Complete_Name", models.CharField(max_length=80)),
                ("Current_Shop", models.CharField(max_length=100, null=True)),
                ("Cost_Center_Name", models.CharField(max_length=100, null=True)),
                ("total_assigned_pl", models.FloatField(default=0)),
                ("total_assigned_cl", models.FloatField(default=0)),
                ("total_assigned_sl", models.FloatField(default=0)),
                ("total_available_pl", models.FloatField(default=0)),
                ("total_available_cl", models.FloatField(default=0)),
                ("total_available_sl", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="todays_attendance2",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Ticket_No",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("p_time", models.CharField(blank=True, max_length=100)),
                ("date_t", models.DateField(blank=True)),
                ("submission", models.CharField(max_length=200, null=True)),
                ("sym_issue", models.CharField(max_length=200, null=True)),
                ("containment_issue", models.CharField(max_length=200, null=True)),
                ("quarantine_issue", models.CharField(max_length=200, null=True)),
                (
                    "submission_from_company",
                    models.CharField(max_length=200, null=True),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("dep", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
